version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: database
    environment:
      POSTGRES_DB: database
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  auth-service:
    build:
      context: ./auth
      dockerfile: Dockerfile
    container_name: auth-service
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=production
      - SPRING_DATASOURCE_URL=jdbc:postgresql://database:5432/database
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
    depends_on:
      - postgres
#  nginx:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    container_name: nginx
#    ports:
#      - "80:80"
#    depends_on:
#      - auth-service

volumes:
  postgres_data: